//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServicesDemo.ConvertServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConvertServiceReference.ConvertSoap")]
    public interface ConvertSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WebServicesDemo.ConvertServiceReference.HelloWorldResponse HelloWorld(WebServicesDemo.ConvertServiceReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServicesDemo.ConvertServiceReference.HelloWorldResponse> HelloWorldAsync(WebServicesDemo.ConvertServiceReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FahrenheitToCelcius", ReplyAction="*")]
        double FahrenheitToCelcius(double Fahrenheit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FahrenheitToCelcius", ReplyAction="*")]
        System.Threading.Tasks.Task<double> FahrenheitToCelciusAsync(double Fahrenheit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CelciusToFahrenheit", ReplyAction="*")]
        double CelciusToFahrenheit(double Celcius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CelciusToFahrenheit", ReplyAction="*")]
        System.Threading.Tasks.Task<double> CelciusToFahrenheitAsync(double Celcius);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WebServicesDemo.ConvertServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WebServicesDemo.ConvertServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServicesDemo.ConvertServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WebServicesDemo.ConvertServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConvertSoapChannel : WebServicesDemo.ConvertServiceReference.ConvertSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConvertSoapClient : System.ServiceModel.ClientBase<WebServicesDemo.ConvertServiceReference.ConvertSoap>, WebServicesDemo.ConvertServiceReference.ConvertSoap {
        
        public ConvertSoapClient() {
        }
        
        public ConvertSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConvertSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConvertSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConvertSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServicesDemo.ConvertServiceReference.HelloWorldResponse WebServicesDemo.ConvertServiceReference.ConvertSoap.HelloWorld(WebServicesDemo.ConvertServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WebServicesDemo.ConvertServiceReference.HelloWorldRequest inValue = new WebServicesDemo.ConvertServiceReference.HelloWorldRequest();
            inValue.Body = new WebServicesDemo.ConvertServiceReference.HelloWorldRequestBody();
            WebServicesDemo.ConvertServiceReference.HelloWorldResponse retVal = ((WebServicesDemo.ConvertServiceReference.ConvertSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServicesDemo.ConvertServiceReference.HelloWorldResponse> WebServicesDemo.ConvertServiceReference.ConvertSoap.HelloWorldAsync(WebServicesDemo.ConvertServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServicesDemo.ConvertServiceReference.HelloWorldResponse> HelloWorldAsync() {
            WebServicesDemo.ConvertServiceReference.HelloWorldRequest inValue = new WebServicesDemo.ConvertServiceReference.HelloWorldRequest();
            inValue.Body = new WebServicesDemo.ConvertServiceReference.HelloWorldRequestBody();
            return ((WebServicesDemo.ConvertServiceReference.ConvertSoap)(this)).HelloWorldAsync(inValue);
        }
        
        public double FahrenheitToCelcius(double Fahrenheit) {
            return base.Channel.FahrenheitToCelcius(Fahrenheit);
        }
        
        public System.Threading.Tasks.Task<double> FahrenheitToCelciusAsync(double Fahrenheit) {
            return base.Channel.FahrenheitToCelciusAsync(Fahrenheit);
        }
        
        public double CelciusToFahrenheit(double Celcius) {
            return base.Channel.CelciusToFahrenheit(Celcius);
        }
        
        public System.Threading.Tasks.Task<double> CelciusToFahrenheitAsync(double Celcius) {
            return base.Channel.CelciusToFahrenheitAsync(Celcius);
        }
    }
}
